control_center_ssl_java_arg_buildout: "-Djavax.net.ssl.keyStore={{keystore_path}} -Djavax.net.ssl.trustStore={{truststore_path}} -Djavax.net.ssl.keyStorePassword={{keystore_storepass}} -Djavax.net.ssl.trustStorePassword={{truststore_storepass}}"
control_center_ssl_java_arg: "{{ control_center_ssl_java_arg_buildout if schema_registry_ssl_enabled|bool else '' }}"

control_center_log4j_file: /etc/confluent-control-center/control-center_log4j.properties

control_center_open_file_limit: "{{open_file_limit}}"
control_center_service_overrides:
  LimitNOFILE: "{{control_center_open_file_limit}}"
control_center_service_environment_overrides:
  CONTROL_CENTER_HEAP_OPTS: "-Xmx6g"
  CONTROL_CENTER_OPTS: "{{control_center_ssl_java_arg}}"
  CONTROL_CENTER_LOG4J_OPTS: "-Dlog4j.configuration=file:{{control_center_log4j_file}}"

control_center_packages:
  - confluent-control-center
  - confluent-control-center-fe

control_center:
  user: cp-control-center
  group: confluent
  config_file: /etc/confluent-control-center/control-center-production.properties
  log4j_file: "{{control_center_log4j_file}}"
  appender_log_path: /var/log/confluent/control-center/
  c3appender_log_name: control-center.log
  c3appender_max_log_files: 10
  c3appender_log_file_size: 100MB
  streamsappender_log_name: control-center-streams.log
  streamsappender_max_log_files: 10
  streamsappender_log_file_size: 100MB
  kafkaappender_log_name: control-center-kafka.log
  kafkaappender_max_log_files: 10
  kafkaappender_log_file_size: 100MB
  systemd_file: /usr/lib/systemd/system/confluent-control-center.service
  systemd_override: /etc/systemd/system/confluent-control-center.service.d
  service_name: confluent-control-center
  properties:
    confluent.controlcenter.streams.num.stream.threads: 8
    confluent.controlcenter.data.dir: /var/lib/confluent/control-center
    confluent.controlcenter.ksql.enable: 'true'
    confluent.controlcenter.schema.registry.enable: 'true'
  systemd:
    enabled: yes
    state: started
