---
- name: Delete SSL Certificate Directory
  file:
    path: /var/ssl/private
    state: absent

- name: Create SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: directory
    mode: 0755

- name: Create Keystore and Truststore with Self Signed Certs
  include_tasks: self_signed_certs.yml
  when: self_signed|bool

- name: Create Keystore and Truststore with Custom Certs
  include_tasks: custom_certs.yml
  when: ssl_custom_certs|bool

- name: Copy Keystore and Truststore to Host
  include_tasks: provided_keystore_and_truststore.yml
  when: ssl_provided_keystore_and_truststore|bool

- set_fact:
    certs_updated: true

- name: Delete SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: absent
