---
- name: Copy Host Keystore to Host
  copy:
    src: "{{ssl_keystore_filepath}}"
    dest: "{{keystore_path}}"

- name: Copy Host Truststore to Host
  copy:
    src: "{{ssl_truststore_filepath}}"
    dest: "{{truststore_path}}"
