# Install Packages
- name: Install the Kafka Rest Packages
  yum:
    name: "{{item}}-{{confluent.package_version}}"
    state: latest
  loop: "{{kafka_rest_packages}}"
  when: ansible_os_family == "RedHat"

- name: Install the Kafka Rest Packages
  apt:
    name: "{{item}}={{confluent.package_version}}"
    update_cache: yes
  loop: "{{kafka_rest_packages}}"
  when: ansible_os_family == "Debian"

# Configure environment
- name: Create Kafka Rest Group
  group:
    name: "{{kafka_rest.group}}"

- name: Create Kafka Rest User
  user:
    name: "{{kafka_rest.user}}"
    comment: "Kafka REST User"
    system: yes
    group: "{{kafka_rest.group}}"

- name: Create Keytabs Directory
  file:
    path: "{{kerberos.keytab_dir}}"
    group: "{{kafka_rest.group}}"
    mode: '650'
    recurse: yes
  when: sasl_protocol == 'kerberos'

- name: Copy in Keytab File
  copy:
    src: "{{kafka_rest_kerberos_keytab_path}}"
    dest: "{{kerberos.keytab_dir}}/{{kafka_rest_kerberos_keytab_path | basename}}"
    mode: '600'
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  when: sasl_protocol == 'kerberos'
  notify:
    - restart kafka-rest

- name: Create Kafka Rest Config
  template:
    src: kafka-rest.properties.j2
    dest: "{{kafka_rest.config_file}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  notify:
    - restart kafka-rest

- name: Create Logs Directory
  file:
    path: "{{kafka_rest.appender_log_path}}"
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
    mode: '764'
    recurse: yes

- name: Create Kafka Rest log4j Config
  template:
    src: kafka-rest_log4j.properties.j2
    dest: "{{kafka_rest.log4j_file}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  notify:
    - restart kafka-rest

- name: Create Service Override Directory
  file:
    path: "{{kafka_rest.systemd_override}}"
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
    state: directory
    mode: 0640

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{kafka_rest.systemd_override}}/override.conf"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  notify:
    - reload systemd
    - restart kafka-rest

- name: Certs were Updated - Trigger Restart
  command: /bin/true
  notify: restart kafka-rest
  when: certs_updated|bool

- meta: flush_handlers

- name: Start Kafka Rest Service
  systemd:
    name: "{{kafka_rest.service_name}}"
    enabled: "{{kafka_rest.systemd.enabled}}"
    state: "{{kafka_rest.systemd.state}}"
