ksql_open_file_limit: "{{open_file_limit}}"
ksql_streams_state_dir: /var/lib/kafka-streams

ksql_jaas_file: /etc/ksql/ksql-server_jaas.conf
ksql_jaas_java_arg_buildout: "-Djava.security.auth.login.config={{ksql_jaas_file}}"
ksql_jaas_java_arg: "{{ ksql_jaas_java_arg_buildout if sasl_protocol == 'kerberos' else '' }}"

ksql_jolokia_java_arg_buildout: "-javaagent:{{jolokia_jar_path}}=port={{ksql_jolokia_port}},host=0.0.0.0"
ksql_jolokia_java_arg: "{{ ksql_jolokia_java_arg_buildout if jolokia_enabled|bool else '' }}"

ksql_ssl_java_arg_buildout: "-Djavax.net.ssl.keyStore={{keystore_path}} -Djavax.net.ssl.trustStore={{truststore_path}} -Djavax.net.ssl.keyStorePassword={{keystore_storepass}} -Djavax.net.ssl.trustStorePassword={{truststore_storepass}}"
ksql_ssl_java_arg: "{{ ksql_ssl_java_arg_buildout if schema_registry_ssl_enabled|bool else '' }}"

ksql_log4j_file: /etc/ksql/ksql-server_log4j.properties

ksql_opts_buildout: "{{ ksql_jolokia_java_arg + ' ' + ksql_jaas_java_arg + ' ' + ksql_ssl_java_arg if ksql_jolokia_java_arg != '' or ksql_jaas_java_arg != '' or ksql_ssl_java_arg != '' else '' }}"

ksql_service_environment_overrides:
  KSQL_HEAP_OPTS: "-Xmx3g"
  KSQL_OPTS: "{{ ksql_opts_buildout }}"
  KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:{{ksql_log4j_file}}"
ksql_service_overrides:
  LimitNOFILE: "{{ksql_open_file_limit}}"

ksql_packages:
  - confluent-ksql
  - confluent-security

ksql:
  config_file: /etc/ksql/ksql-server.properties
  log4j_file: "{{ksql_log4j_file}}"
  appender_log_path: /var/log/confluent/ksql/
  appender_log_name: ksql.log
  appender_max_log_files: 10
  appender_log_file_size: 100MB
  streams_appender_log_name: ksql-streams.log
  streams_appender_max_log_files: 10
  streams_appender_log_file_size: 100MB
  kafka_appender_log_name: ksql-kafka.log
  kafka_appender_max_log_files: 10
  kafka_appender_log_file_size: 100MB
  service_name: confluent-ksql
  systemd_file: /usr/lib/systemd/system/confluent-ksql.service
  systemd_override: /etc/systemd/system/confluent-ksql.service.d
  user: cp-ksql
  group: confluent
  streamsDataDir: "{{ksql_streams_state_dir}}"
  systemd:
    enabled: yes
    state: started
  properties:
    application.id: ksql-server
    ksql.internal.topic.replicas: 3
    ksql.streams.replication.factor: 3
    ksql.streams.state.dir: "{{ksql_streams_state_dir}}"
    ksql.streams.num.standby.replicas: 1
    ksql.streams.producer.delivery.timeout.ms: 2147483647
    ksql.streams.producer.max.block.ms: 9223372036854775807
