kerberos:
  redhat_packages:
    - krb5-libs
    - krb5-workstation
  ubuntu_packages:
    - python-selinux
    - krb5-user
  dns_lookup_realm: "false"
  dns_lookup_kdc: "false"
  ticket_lifetime: "24h"
  renew_lifetime: "7d"
  forwardable: "true"
  udp_preference_limit: 1
  default_tkt_enctypes: aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arc-four-hmac rc4-hmac
  default_tgs_enctypes: aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arc-four-hmac rc4-hmac
  permitted_enctypes: aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arc-four-hmac rc4-hmac
