- name: Host Prerequisites
  hosts: zookeeper:kafka_broker:control_center
  tasks:
  - import_role:
      name: confluent.common
  - import_role:
      name: confluent.kerberos
    when: sasl_protocol == "kerberos" and kerberos_configure|bool
  - import_role:
      name: confluent.ssl
    when: ssl_enabled|bool

- name: Zookeeper Provisioning
  hosts: zookeeper
  gather_facts: no
  tags:
    - zookeeper
  tasks:
  - import_role:
      name: confluent.zookeeper

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  gather_facts: no
  tags:
    - kafka_broker
  tasks:
  - import_role:
      name: confluent.kafka_broker

- name: Schema Registry Provisioning
  hosts: schema_registry
  gather_facts: no
  tags:
    - schema_registry
  tasks:
  - import_role:
      name: confluent.schema_registry

- name: Kafta Connect Provisioning
  hosts: kafka_connect
  gather_facts: no
  tags:
    - kafka_connect
  tasks:
  - import_role:
      name: confluent.kafka_connect

- name: KSQL Provisioning
  hosts: ksql
  gather_facts: no
  tags:
    - ksql
  tasks:
  - import_role:
      name: confluent.ksql

- name: Kafka Rest Provisioning
  hosts: kafka_rest
  gather_facts: no
  tags:
    - kafka_rest
  tasks:
  - import_role:
      name: confluent.kafka_rest

- name: Control Center Provisioning
  hosts: control_center
  gather_facts: no
  tags:
    - control_center
  tasks:
  - import_role:
      name: confluent.control_center