all:
  children:
    zookeeper:
      hosts:
        ec2-35-180-41-80.eu-west-3.compute.amazonaws.com: null
    kafka_broker:
      hosts:
        ec2-35-180-208-255.eu-west-3.compute.amazonaws.com: null
    control_center:
      hosts:
        ec2-15-188-15-113.eu-west-3.compute.amazonaws.com: null
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true
    ssl_key_filepath: kafka-test.pem
    ansible_ssh_private_key_file: kafka-test.pem