confluent_common:
  repository:
    debian:
      key_url: "https://packages.confluent.io/deb/{{confluent.repo_version}}/archive.key"
      repository: "deb [arch=amd64] https://packages.confluent.io/deb/{{confluent.repo_version}} stable main"
    redhat:
      main:
        baseurl: "https://packages.confluent.io/rpm/{{confluent.repo_version}}"
        gpgcheck: 1
        gpgkey: "https://packages.confluent.io/rpm/{{confluent.repo_version}}/archive.key"
        enabled: 1
      dist:
        baseurl: "https://packages.confluent.io/rpm/{{confluent.repo_version}}/7"
        gpgcheck: 1
        gpgkey: "https://packages.confluent.io/rpm/{{confluent.repo_version}}/archive.key"
        enabled: 1

install_java: true
redhat_java_package_name: java-1.8.0-openjdk
debian_java_package_name: openjdk-8-jdk
ubuntu_java_package_name: openjdk-8-jdk
ubuntu_java_repository: ppa:openjdk-r/ppa

jolokia_version: 1.6.2
