- import_tasks: ubuntu_jvm.yml
  when:
    - install_java|bool
    - ansible_distribution == "Ubuntu"

- import_tasks: debian_jvm.yml
  when: ansible_distribution == 'Debian'

- name: Add Confluent apt key
  apt_key:
    url: "{{confluent_common.repository.debian.key_url}}"
    state: present
- name: Add Confluent apt repo
  apt_repository:
    repo: "{{confluent_common.repository.debian.repository}}"
    state: present
