- name: Install Java
  yum:
    name: "{{redhat_java_package_name}}"
    state: present
  when: install_java|bool

- name: Add Confluent Dist Yum Repo
  yum_repository:
    name: Confluent.dist
    file: confluent
    description: "Confluent repository (dist)"
    baseurl: "{{confluent_common.repository.redhat.dist.baseurl}}"
    gpgcheck: "{{confluent_common.repository.redhat.dist.gpgcheck}}"
    gpgkey: "{{confluent_common.repository.redhat.dist.gpgkey}}"
    enabled: "{{confluent_common.repository.redhat.dist.enabled}}"
  notify: yum-clean-all

- name: Add Confluent Yum Repo
  yum_repository:
    name: Confluent
    file: confluent
    description: "Confluent repository"
    baseurl: "{{confluent_common.repository.redhat.main.baseurl}}"
    gpgcheck: "{{confluent_common.repository.redhat.main.gpgcheck}}"
    gpgkey: "{{confluent_common.repository.redhat.main.gpgkey}}"
    enabled: "{{confluent_common.repository.redhat.main.enabled}}"
  notify: yum-clean-all

- meta: flush_handlers
